const providers=['openrouter','openai','anthropic','google','custom'];
let models=[], catalog=[], state={q:'',provider:'all',weight:'all',modality:'all',reasoning:false,sort:'displayName',editing:null,showAdd:false,msg:'',catalogQuery:''};
const $=s=>document.querySelector(s), fmt=n=>n==null?'—':`$${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`, compact=n=>n?Intl.NumberFormat(undefined,{notation:'compact'}).format(n):'—', standard=m=>m.pricingVariants.find(p=>p.variantName==='standard')||m.pricingVariants[0];
async function api(path,opts={}){const res=await fetch(`/api${path}`,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts}); const text=await res.text(); const data=text?JSON.parse(text):null; if(!res.ok)throw Error(data?.error||`${path} failed: ${res.status}`); return data;}
async function init(){try{const data=await api('/models');models=data.models||[];}catch(e){state.msg=`API unavailable: ${e.message}`;models=await restoreLocal();} render();}
async function restoreLocal(){const data=await fetch('./defaults/models.json').then(r=>r.json()); const now=new Date().toISOString(); return data.map(m=>({...m,isActive:true,isStale:false,addedAt:now,lastSyncedAt:now,userOverriddenFields:[]}));}
async function refresh(){const data=await api('/models');models=data.models||[];}
async function saveModel(m){const saved=await api(`/models${m.id?`/${encodeURIComponent(m.id)}`:''}`,{method:m.id?'PATCH':'POST',body:JSON.stringify(m)}); await refresh(); state.msg=`Saved ${saved.model.displayName}.`; render();}
async function archiveModel(id){await api(`/models/${encodeURIComponent(id)}`,{method:'DELETE'}); await refresh(); render();}
async function deleteModel(id){await api(`/models/${encodeURIComponent(id)}?hard=true`,{method:'DELETE'}); await refresh(); render();}
async function restore(){const data=await api('/defaults/restore',{method:'POST'}); models=data.models; state.msg=`Restored ${models.length} default models.`; render();}
async function syncOpenRouter(){state.msg='Syncing OpenRouter through Worker…'; render(); try{const data=await api('/providers/openrouter/sync',{method:'POST'}); catalog=data.catalog||[]; await refresh(); state.msg=`Synced OpenRouter catalog: ${catalog.length} models available. Use Add model to import catalog entries.`; render();}catch(e){state.msg=e.message; render();}}
async function syncArtificialAnalysis(){state.msg='Syncing Artificial Analysis enrichment through Worker…'; render(); try{const data=await api('/enrichment/sync',{method:'POST'}); await refresh(); state.msg=`Artificial Analysis enrichment updated ${data.enriched} tracked models from ${data.records} records.`; render();}catch(e){state.msg=e.message; render();}}
function tags(h){h=h.toLowerCase();let t=[]; if(/code|program/.test(h))t.push('coding'); if(/reason|math|r1|thinking/.test(h))t.push('reasoning'); if(/image|vision|multimodal/.test(h))t.push('multimodal'); if(/agent/.test(h))t.push('agentic workflows'); if(/open|llama|qwen|mistral|deepseek/.test(h))t.push('open ecosystem'); return t.slice(0,3)}
function filtered(){return models.filter(m=>m.isActive!==false).filter(m=>(state.provider==='all'||m.provider===state.provider)&&(state.weight==='all'||m.weightClass===state.weight)&&(state.modality==='all'||(m.modalities||[]).includes(state.modality))&&(!state.reasoning||m.reasoning)&&`${m.displayName} ${m.family} ${(m.bestForTags||[]).join(' ')} ${m.bestForNote}`.toLowerCase().includes(state.q.toLowerCase())).sort((a,b)=>{let av=state.sort==='input'?standard(a).inputPer1M:state.sort==='output'?standard(a).outputPer1M:a[state.sort], bv=state.sort==='input'?standard(b).inputPer1M:state.sort==='output'?standard(b).outputPer1M:b[state.sort]; return typeof av==='number'?av-bv:String(av).localeCompare(String(bv));});}
function render(){const active=models.filter(m=>m.isActive!==false).length, archived=models.length-active; $('#root').innerHTML=`<header><div><p class="eyebrow">Model Curator</p><h1>AI model cost & capability reference</h1><p>Maintain a personal catalog, compare token pricing, and keep provider metadata visible in one mobile-first table.</p></div><div class="header-actions"><button id="sync">↻ Refresh OpenRouter</button><button id="aaSync">◆ Enrich Artificial Analysis</button></div></header><main><section class="toolbar"><label>⌕<input id="q" placeholder="Search name, family, tags…" value="${esc(state.q)}"></label>${select('provider',['all',...providers])}${select('weight',['all','proprietary','open-weights','restricted'])}${select('modality',['all','text','image','audio','video','pdf'])}<label class="check"><input id="reasoning" type="checkbox" ${state.reasoning?'checked':''}> Reasoning</label>${select('sort',['displayName','input','output','contextWindow','family'])}<button id="add">＋ Add model</button><button id="restore" class="secondary">↺ Restore defaults</button></section>${state.msg?`<p class="notice">${esc(state.msg)}</p>`:''}<section class="stats"><span>▣ ${active} active models</span><span>${archived} archived</span><span>${catalog.length} catalog candidates</span></section><section class="table"><div class="thead"><span>Name</span><span>Family</span><span>Class</span><span>Context</span><span>Input</span><span>Output</span><span>Capabilities</span><span>Synced</span><span>Actions</span></div>${filtered().map(row).join('')}</section></main>${state.showAdd||state.editing?editor():''}`; bind();}
function select(id,opts){return `<select id="${id}">${opts.map(o=>`<option ${state[id]===o?'selected':''}>${o}</option>`).join('')}</select>`}
function row(m){let p=standard(m);return `<details class="row"><summary><span><strong>${esc(m.displayName)}</strong><small>${m.provider} · ${esc(m.providerModelId)}</small></span><span>${esc(m.family)}</span><span class="pill">${m.weightClass}</span><span>${compact(m.contextWindow)}</span><span>${fmt(p.inputPer1M)}</span><span>${fmt(p.outputPer1M)}</span><span>${m.reasoning?'Reasoning':'Standard'} · ${esc((m.bestForTags||[])[0]||'general')}</span><span>${m.isStale?'Stale':new Date(m.lastSyncedAt||m.addedAt).toLocaleDateString()}</span><span class="actions"><button data-edit="${m.id}">Edit</button><button data-archive="${m.id}">Archive</button><button data-delete="${m.id}">Delete</button></span></summary><div class="detail"><p>${esc(m.bestForNote)}</p><div>${(m.bestForTags||[]).map(t=>`<b>${esc(t)}</b>`).join('')}</div><p>Modalities: ${(m.modalities||[]).join(', ')} · Tools: ${m.toolUse?'yes':'no'} · Structured output: ${m.structuredOutput?'yes':'no'} · Max output: ${compact(m.maxOutputTokens)}</p><table><tbody>${(m.pricingVariants||[]).map(v=>`<tr><td>${esc(v.variantName)}</td><td>in ${fmt(v.inputPer1M)}</td><td>out ${fmt(v.outputPer1M)}</td><td>cache ${fmt(v.cachedInputPer1M)}</td><td>${v.reasoningOutputPer1M?`reasoning ${fmt(v.reasoningOutputPer1M)}`:''}</td></tr>`).join('')}</tbody></table>${m.sourceUrl?`<a target="_blank" href="${esc(m.sourceUrl)}">Source link</a>`:''}</div></details>`}
function editor(){let m=state.editing||{provider:'custom',displayName:'',providerModelId:'',family:'',weightClass:'proprietary',sizeTier:'medium',contextWindow:0,modalities:['text'],toolUse:false,structuredOutput:false,reasoning:false,bestForTags:[],bestForNote:'',pricingVariants:[{variantName:'standard',inputPer1M:0,outputPer1M:0,cachedInputPer1M:null,unit:'per_1m_tokens'}]};let p=standard(m);return `<div class="modal"><form id="form"><h2>${m.id?'Edit':'Add'} model</h2>${catalog.length&&!m.id?catalogPicker():''}<input name="displayName" required placeholder="Display name" value="${esc(m.displayName)}"><input name="providerModelId" required placeholder="Provider model ID" value="${esc(m.providerModelId)}"><select name="provider">${providers.map(pv=>`<option ${m.provider===pv?'selected':''}>${pv}</option>`)}</select><input name="family" placeholder="Family" value="${esc(m.family)}"><div class="grid"><input name="contextWindow" type="number" placeholder="Context tokens" value="${m.contextWindow||0}"><input name="input" type="number" step="0.01" placeholder="Input $/1M" value="${p.inputPer1M||0}"><input name="output" type="number" step="0.01" placeholder="Output $/1M" value="${p.outputPer1M||0}"></div><textarea name="bestForNote" placeholder="Best for note">${esc(m.bestForNote)}</textarea><input name="bestForTags" placeholder="Tags, comma separated" value="${esc((m.bestForTags||[]).join(', '))}"><label><input name="reasoning" type="checkbox" ${m.reasoning?'checked':''}> Supports reasoning/thinking</label><menu><button type="button" id="cancel">Cancel</button><button>✓ Save</button></menu></form></div>`}
function catalogPicker(){let q=state.catalogQuery.toLowerCase();let all=catalog.filter(c=>`${c.displayName} ${c.providerModelId} ${c.family}`.toLowerCase().includes(q));let matches=all.slice(0,100);return `<label class="catalog-search">Search OpenRouter catalog<input id="catalogQuery" placeholder="Type a model name, provider, or ID…" value="${esc(state.catalogQuery)}"></label><select id="pick" size="${Math.min(Math.max(matches.length+1,4),10)}"><option value="">${matches.length ? `Pick from ${matches.length}${all.length>100?' of 100+':''} matches…` : 'No matching OpenRouter models'}</option>${matches.map(c=>`<option value="${c.id}">${esc(c.displayName)} — ${esc(c.providerModelId)}</option>`).join('')}</select>`}
function renderAndRestore(id,start,end){render();let el=$('#'+id);if(el){el.focus();if(typeof el.setSelectionRange==='function')el.setSelectionRange(start,end);}}
function bind(){['provider','weight','modality','sort'].forEach(id=>$('#'+id)?.addEventListener('input',e=>{state[id]=e.target.value;render()})); $('#q')?.addEventListener('input',e=>{state.q=e.target.value;renderAndRestore('q',e.target.selectionStart,e.target.selectionEnd)}); $('#reasoning')?.addEventListener('change',e=>{state.reasoning=e.target.checked;render()}); $('#sync').onclick=syncOpenRouter; $('#aaSync').onclick=syncArtificialAnalysis; $('#add').onclick=()=>{state.showAdd=true;state.catalogQuery='';render()}; $('#restore').onclick=restore; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{state.editing=models.find(m=>m.id===e.target.dataset.edit);render()}); document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=e=>archiveModel(e.target.dataset.archive)); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>deleteModel(e.target.dataset.delete)); $('#cancel')?.addEventListener('click',()=>{state.showAdd=false;state.editing=null;render()}); $('#catalogQuery')?.addEventListener('input',e=>{state.catalogQuery=e.target.value;renderAndRestore('catalogQuery',e.target.selectionStart,e.target.selectionEnd)}); $('#pick')?.addEventListener('change',e=>{state.editing=catalog.find(c=>c.id===e.target.value);render()}); $('#form')?.addEventListener('submit',async e=>{e.preventDefault();let f=new FormData(e.target), base=state.editing||{}; let m={...base,provider:f.get('provider'),displayName:f.get('displayName'),providerModelId:f.get('providerModelId'),family:f.get('family'),contextWindow:Number(f.get('contextWindow')),reasoning:!!f.get('reasoning'),bestForNote:f.get('bestForNote'),bestForTags:String(f.get('bestForTags')).split(',').map(t=>t.trim()).filter(Boolean),isActive:true,lastSyncedAt:new Date().toISOString(),userOverriddenFields:['displayName','providerModelId','family','contextWindow','pricingVariants','bestForNote','bestForTags','reasoning'],pricingVariants:[{...(base.pricingVariants?.[0]||{}),variantName:'standard',inputPer1M:Number(f.get('input')),outputPer1M:Number(f.get('output')),unit:'per_1m_tokens'}]}; state.showAdd=false;state.editing=null; await saveModel(m);});}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
init();
